import { ProductDataProps } from "./types/product";

export const APP_NAME = "Aucto";
export const GITHUB_REPO = "https://github.com/a0v0/aucto";
export const SITE_URL = "https://aucto-site.vercel.app/";
export const ProductData: ProductDataProps[] = [
  {
    images: [
      "https://source.unsplash.com/1920x1080/?quadcopter,drone,sky",
      "https://source.unsplash.com/1920x1080/?drones,aerial,technology",
      "https://source.unsplash.com/1920x1080/?uav,flying,landscape",
    ],
    slug: "1",
    productName: "Advanced Quadcopter Drone",
    basePrice: 799.99,
    endsInHours: 48,
    description:
      "Explore the skies with our advanced quadcopter drone. Equipped with the latest technology, it offers stable flight, 4K camera, and long battery life. Capture breathtaking aerial views.",
    ratings: 4.5,
    activeBids: 15,
    watchers: 150,
    totalBids: 1200,
    reviews: 45,
    bidIncrementBy: 50,
    details: [
      { key: "Brand", value: "DroneTech" },
      { key: "Model", value: "SkyMaster X-500" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "Black" },
      { key: "Camera", value: "4K Ultra HD" },
      { key: "Flight Time", value: "25 minutes" },
      { key: "Max Range", value: "1000 meters" },
      { key: "GPS", value: "Yes" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?laptop,technology",
      "https://source.unsplash.com/1920x1080/?notebook,office",
      "https://source.unsplash.com/1920x1080/?computer,workspace",
    ],
    slug: "2",
    productName: "High-Performance Laptop",
    basePrice: 1299.99,
    endsInHours: 72,
    description:
      "Experience blazing-fast performance with our high-performance laptop. Ideal for gaming and content creation, it features a powerful processor and a high-refresh-rate display.",
    ratings: 4.8,
    activeBids: 12,
    watchers: 120,
    totalBids: 900,
    reviews: 28,
    bidIncrementBy: 75,
    details: [
      { key: "Brand", value: "TechMasters" },
      { key: "Model", value: "SuperBook Pro" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "Space Gray" },
      { key: "Processor", value: "Intel Core i9" },
      { key: "RAM", value: "32 GB" },
      { key: "Display", value: "17.3 inches, 144Hz" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?headphones,music",
      "https://source.unsplash.com/1920x1080/?wireless,earphones",
      "https://source.unsplash.com/1920x1080/?audio,sound",
    ],
    slug: "3",
    productName: "Wireless Noise-Canceling Headphones",
    basePrice: 249.99,
    endsInHours: 36,
    description:
      "Immerse yourself in music with our wireless noise-canceling headphones. Enjoy crystal-clear sound and block out distractions wherever you go.",
    ratings: 4.7,
    activeBids: 8,
    watchers: 80,
    totalBids: 600,
    reviews: 22,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "SoundBliss" },
      { key: "Model", value: "QuietTunes 900" },
      { key: "Color", value: "Midnight Black" },
      { key: "Noise Cancellation", value: "Active Noise-Canceling" },
      { key: "Battery Life", value: "30 hours" },
      { key: "Connectivity", value: "Bluetooth 5.0" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?smartphone,technology",
      "https://source.unsplash.com/1920x1080/?mobile,communication",
      "https://source.unsplash.com/1920x1080/?cellphone,gadget",
    ],
    slug: "4",
    productName: "Smartphone with AI Camera",
    basePrice: 599.99,
    endsInHours: 24,
    description:
      "Experience the future of photography with our smartphone featuring AI-powered camera technology. Capture stunning photos and videos effortlessly.",
    ratings: 4.6,
    activeBids: 20,
    watchers: 180,
    totalBids: 1400,
    reviews: 50,
    bidIncrementBy: 40,
    details: [
      { key: "Brand", value: "TechWonders" },
      { key: "Model", value: "AI Vision X7" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "Mystic Silver" },
      { key: "Camera", value: "Triple AI Camera" },
      { key: "Storage", value: "128 GB" },
      { key: "Display", value: "6.5 inches, Super AMOLED" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?gaming-laptop,technology",
      "https://source.unsplash.com/1920x1080/?gamer,computer",
      "https://source.unsplash.com/1920x1080/?gaming-setup,laptop",
    ],
    slug: "5",
    productName: "Gaming Laptop for Pro Gamers",
    basePrice: 1799.99,
    endsInHours: 96,
    description:
      "Elevate your gaming experience with our gaming laptop designed for pro gamers. Featuring high-performance hardware and a blazing-fast refresh rate.",
    ratings: 4.9,
    activeBids: 25,
    watchers: 200,
    totalBids: 1800,
    reviews: 60,
    bidIncrementBy: 80,
    details: [
      { key: "Brand", value: "GamerXtreme" },
      { key: "Model", value: "ProGamer 9000" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "RGB Lighting" },
      { key: "Processor", value: "Intel Core i7" },
      { key: "GPU", value: "NVIDIA GeForce RTX 3080" },
      { key: "Display", value: "15.6 inches, 240Hz" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?smartwatch,technology",
      "https://source.unsplash.com/1920x1080/?wearable,watch",
      "https://source.unsplash.com/1920x1080/?health,fitness",
    ],
    slug: "6",
    productName: "Smartwatch with Health Monitoring",
    basePrice: 149.99,
    endsInHours: 36,
    description:
      "Stay on top of your health and fitness with our smartwatch featuring advanced health monitoring capabilities. Track your activity, heart rate, and more.",
    ratings: 4.3,
    activeBids: 10,
    watchers: 90,
    totalBids: 800,
    reviews: 35,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "HealthTech" },
      { key: "Model", value: "HealthWatch 3" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "Slate Gray" },
      { key: "Health Monitoring", value: "Heart Rate, Sleep, Fitness" },
      { key: "Display", value: "1.3 inches, AMOLED" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?earphones,headphones",
      "https://source.unsplash.com/1920x1080/?wireless,earbuds",
      "https://source.unsplash.com/1920x1080/?audio,gadget",
    ],
    slug: "7",
    productName: "Wireless Earbuds with Noise Cancellation",
    basePrice: 129.99,
    endsInHours: 48,
    description:
      "Enjoy your music with crystal-clear sound and no distractions using our wireless earbuds with noise cancellation technology.",
    ratings: 4.7,
    activeBids: 12,
    watchers: 100,
    totalBids: 950,
    reviews: 42,
    bidIncrementBy: 35,
    details: [
      { key: "Brand", value: "SoundMasters" },
      { key: "Model", value: "QuietBeats Pro" },
      { key: "Color", value: "Matte Black" },
      { key: "Noise Cancellation", value: "Active Noise-Canceling" },
      { key: "Battery Life", value: "24 hours" },
      { key: "Connectivity", value: "Bluetooth 5.2" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?watch,wristwatch",
      "https://source.unsplash.com/1920x1080/?timepiece,fashion",
      "https://source.unsplash.com/1920x1080/?luxury,timekeeping",
    ],

    slug: "8",
    productName: "Luxury Wristwatch",
    basePrice: 999.99,
    endsInHours: 72,
    description:
      "Elevate your style with our luxury wristwatch. Crafted with precision and elegance, it's the perfect accessory for any occasion.",
    ratings: 4.9,
    activeBids: 18,
    watchers: 120,
    totalBids: 1100,
    reviews: 48,
    bidIncrementBy: 60,
    details: [
      { key: "Brand", value: "TimeLux" },
      { key: "Model", value: "Elegance 2023" },
      { key: "Color", value: "Rose Gold" },
      { key: "Material", value: "Stainless Steel" },
      { key: "Movement", value: "Automatic" },
      { key: "Water Resistance", value: "50 meters" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?backpack,hiking",
      "https://source.unsplash.com/1920x1080/?outdoor,travel",
      "https://source.unsplash.com/1920x1080/?adventure,camping",
    ],
    slug: "9",
    productName: "Outdoor Adventure Backpack",
    basePrice: 79.99,
    endsInHours: 48,
    description:
      "Gear up for your outdoor adventures with our spacious and durable backpack. It's designed to carry all your essentials comfortably.",
    ratings: 4.4,
    activeBids: 10,
    watchers: 70,
    totalBids: 600,
    reviews: 28,
    bidIncrementBy: 20,
    details: [
      { key: "Brand", value: "AdventureGear" },
      { key: "Model", value: "Explorer 500" },
      { key: "Color", value: "Forest Green" },
      { key: "Capacity", value: "40 liters" },
      { key: "Material", value: "Ripstop Nylon" },
      { key: "Features", value: "Hydration-compatible" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?gaming-mouse,technology",
      "https://source.unsplash.com/1920x1080/?gamer,computer",
      "https://source.unsplash.com/1920x1080/?accessory,hardware",
    ],
    slug: "10",
    productName: "High-Precision Gaming Mouse",
    basePrice: 49.99,
    endsInHours: 24,
    description:
      "Dominate your gaming battles with our high-precision gaming mouse. It offers customizable RGB lighting and responsive controls.",
    ratings: 4.6,
    activeBids: 15,
    watchers: 90,
    totalBids: 750,
    reviews: 32,
    bidIncrementBy: 15,
    details: [
      { key: "Brand", value: "GamerZone" },
      { key: "Model", value: "ProMouse X1" },
      { key: "Color", value: "RGB Spectrum" },
      { key: "DPI", value: "16,000 DPI" },
      { key: "Buttons", value: "8 programmable buttons" },
      { key: "Connection", value: "USB" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?fitness,exercise",
      "https://source.unsplash.com/1920x1080/?workout,health",
      "https://source.unsplash.com/1920x1080/?gym,active",
    ],

    slug: "11",
    productName: "Home Fitness Equipment Set",
    basePrice: 349.99,
    endsInHours: 72,
    description:
      "Stay fit at home with our comprehensive fitness equipment set. It includes everything you need for a full-body workout.",
    ratings: 4.8,
    activeBids: 20,
    watchers: 140,
    totalBids: 1000,
    reviews: 40,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "FitLife" },
      {
        key: "Contents",
        value: "Dumbbells, Resistance Bands, Yoga Mat, and more",
      },
      { key: "Material", value: "High-Quality Materials" },
      { key: "Training Options", value: "Strength, Cardio, and Flexibility" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?telescope,astronomy",
      "https://source.unsplash.com/1920x1080/?observatory,stars",
      "https://source.unsplash.com/1920x1080/?space,galaxy",
    ],

    slug: "12",
    productName: "High-Powered Telescope",
    basePrice: 599.99,
    endsInHours: 96,
    description:
      "Explore the wonders of the night sky with our high-powered telescope. Perfect for stargazing and astronomical observations.",
    ratings: 4.9,
    activeBids: 25,
    watchers: 180,
    totalBids: 1200,
    reviews: 55,
    bidIncrementBy: 50,
    details: [
      { key: "Brand", value: "StellarScope" },
      { key: "Model", value: "AstronomyPro 1200X" },
      { key: "Aperture", value: "150mm" },
      { key: "Focal Length", value: "1400mm" },
      { key: "Magnification", value: "Up to 300x" },
      { key: "Mount Type", value: "Equatorial" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?camera,photography",
      "https://source.unsplash.com/1920x1080/?dslr,photo",
      "https://source.unsplash.com/1920x1080/?lens,shutter",
    ],

    slug: "13",
    productName: "Professional DSLR Camera Kit",
    basePrice: 1299.99,
    endsInHours: 48,
    description:
      "Capture stunning photos and videos with our professional DSLR camera kit. It comes with high-quality lenses and accessories for versatile photography.",
    ratings: 4.7,
    activeBids: 18,
    watchers: 120,
    totalBids: 900,
    reviews: 48,
    bidIncrementBy: 60,
    details: [
      { key: "Brand", value: "PhotoMaster" },
      { key: "Model", value: "ProCapture X1" },
      { key: "Color", value: "Black" },
      { key: "Sensor Type", value: "Full Frame" },
      { key: "Lenses", value: "18-55mm, 50mm prime" },
      { key: "Accessories", value: "Tripod, Camera Bag, and more" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?kitchen,cooking",
      "https://source.unsplash.com/1920x1080/?culinary,food",
      "https://source.unsplash.com/1920x1080/?chef,utensils",
    ],

    slug: "14",
    productName: "Chef's Knife Set with Block",
    basePrice: 99.99,
    endsInHours: 36,
    description:
      "Equip your kitchen with our premium chef's knife set. It includes a variety of knives for precise cutting and a stylish wooden block for storage.",
    ratings: 4.5,
    activeBids: 12,
    watchers: 100,
    totalBids: 800,
    reviews: 38,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "KitchenMaster" },
      {
        key: "Knife Types",
        value: "Chef Knife, Bread Knife, Paring Knife, and more",
      },
      { key: "Material", value: "High-Carbon Stainless Steel" },
      { key: "Block Material", value: "Acacia Wood" },
      { key: "Set Pieces", value: "15 knives with block" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?speaker,audio",
      "https://source.unsplash.com/1920x1080/?sound,entertainment",
      "https://source.unsplash.com/1920x1080/?music,amplifier",
    ],

    slug: "15",
    productName: "Wireless Bluetooth Speaker",
    basePrice: 69.99,
    endsInHours: 24,
    description:
      "Enjoy your favorite music wirelessly with our Bluetooth speaker. It delivers high-quality sound and is perfect for both indoor and outdoor use.",
    ratings: 4.6,
    activeBids: 14,
    watchers: 110,
    totalBids: 850,
    reviews: 40,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "SoundWave" },
      { key: "Model", value: "Harmony 300" },
      { key: "Color", value: "Midnight Blue" },
      { key: "Connectivity", value: "Bluetooth 5.0" },
      { key: "Battery Life", value: "Up to 10 hours" },
      { key: "Water Resistance", value: "IPX5" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?luggage,travel",
      "https://source.unsplash.com/1920x1080/?suitcase,explore",
      "https://source.unsplash.com/1920x1080/?bag,journey",
    ],

    slug: "16",
    productName: "Travel Luggage Set",
    basePrice: 179.99,
    endsInHours: 72,
    description:
      "Travel in style with our durable luggage set. It includes three sizes of suitcases, all designed for easy packing and smooth travels.",
    ratings: 4.8,
    activeBids: 22,
    watchers: 160,
    totalBids: 1200,
    reviews: 55,
    bidIncrementBy: 40,
    details: [
      { key: "Brand", value: "TravelLux" },
      { key: "Set Pieces", value: "Small, Medium, and Large Suitcases" },
      { key: "Material", value: "Hardshell ABS" },
      { key: "Wheels", value: "360-degree spinner wheels" },
      { key: "Handles", value: "Telescopic handles" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?guitar,music",
      "https://source.unsplash.com/1920x1080/?acoustic,instrument",
      "https://source.unsplash.com/1920x1080/?strings,performance",
    ],

    slug: "17",
    productName: "Acoustic Guitar with Case",
    basePrice: 199.99,
    endsInHours: 48,
    description:
      "Unleash your musical talents with our acoustic guitar. It produces rich, warm tones and comes with a protective case for safe storage and transport.",
    ratings: 4.7,
    activeBids: 16,
    watchers: 130,
    totalBids: 950,
    reviews: 42,
    bidIncrementBy: 35,
    details: [
      { key: "Brand", value: "MelodyCraft" },
      { key: "Model", value: "Harmony 3000" },
      { key: "Color", value: "Natural Wood" },
      { key: "Body Material", value: "Mahogany" },
      { key: "Includes", value: "Guitar Case" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?watch,wristwatch",
      "https://source.unsplash.com/1920x1080/?timepiece,fashion",
      "https://source.unsplash.com/1920x1080/?luxury,timekeeping",
    ],

    slug: "18",
    productName: "Classic Men's Wristwatch",
    basePrice: 149.99,
    endsInHours: 48,
    description:
      "Elevate your style with our classic men's wristwatch. It exudes timeless elegance and is suitable for both formal and casual occasions.",
    ratings: 4.5,
    activeBids: 14,
    watchers: 100,
    totalBids: 850,
    reviews: 36,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "TimeClassics" },
      { key: "Model", value: "Elegance 2023" },
      { key: "Color", value: "Silver and Black" },
      { key: "Material", value: "Stainless Steel" },
      { key: "Movement", value: "Automatic" },
      { key: "Water Resistance", value: "50 meters" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?drone,quadcopter",
      "https://source.unsplash.com/1920x1080/?aerial,technology",
      "https://source.unsplash.com/1920x1080/?uav,flying",
    ],

    slug: "19",
    productName: "Compact Foldable Drone",
    basePrice: 299.99,
    endsInHours: 36,
    description:
      "Take to the skies with our compact foldable drone. It's easy to carry, offers HD camera capabilities, and is perfect for capturing aerial moments.",
    ratings: 4.4,
    activeBids: 12,
    watchers: 80,
    totalBids: 700,
    reviews: 25,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "SkyFly" },
      { key: "Model", value: "SkyFold 200" },
      { key: "Year", value: "2023" },
      { key: "Color", value: "Dark Gray" },
      { key: "Camera", value: "HD Camera" },
      { key: "Flight Time", value: "20 minutes" },
      { key: "Max Range", value: "800 meters" },
      { key: "GPS", value: "Yes" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?gaming-keyboard,technology",
      "https://source.unsplash.com/1920x1080/?gamer,computer",
      "https://source.unsplash.com/1920x1080/?accessory,hardware",
    ],

    slug: "20",
    productName: "Mechanical Gaming Keyboard",
    basePrice: 79.99,
    endsInHours: 24,
    description:
      "Elevate your gaming experience with our mechanical gaming keyboard. It offers customizable RGB lighting and ultra-responsive key switches.",
    ratings: 4.6,
    activeBids: 16,
    watchers: 120,
    totalBids: 900,
    reviews: 38,
    bidIncrementBy: 20,
    details: [
      { key: "Brand", value: "GamerZone" },
      { key: "Model", value: "MechKey X3" },
      { key: "Color", value: "RGB Spectrum" },
      { key: "Switches", value: "Cherry MX Red" },
      { key: "Features", value: "N-Key Rollover, Anti-Ghosting" },
      { key: "Connection", value: "USB" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?headphones,music",
      "https://source.unsplash.com/1920x1080/?wireless,earphones",
      "https://source.unsplash.com/1920x1080/?audio,sound",
    ],

    slug: "21",
    productName: "Over-Ear Wireless Headphones",
    basePrice: 129.99,
    endsInHours: 48,
    description:
      "Immerse yourself in your favorite music with our over-ear wireless headphones. Enjoy high-quality audio and comfortable, long-lasting listening.",
    ratings: 4.7,
    activeBids: 14,
    watchers: 110,
    totalBids: 850,
    reviews: 40,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "SoundWave" },
      { key: "Model", value: "AudioBliss Pro" },
      { key: "Color", value: "Slate Gray" },
      { key: "Noise Cancellation", value: "Active Noise-Canceling" },
      { key: "Battery Life", value: "Up to 30 hours" },
      { key: "Connectivity", value: "Bluetooth 5.2" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?backpack,hiking",
      "https://source.unsplash.com/1920x1080/?outdoor,travel",
      "https://source.unsplash.com/1920x1080/?adventure,camping",
    ],

    slug: "22",
    productName: "Hiking Backpack with Hydration",
    basePrice: 69.99,
    endsInHours: 24,
    description:
      "Stay hydrated and organized on your hiking adventures with our hiking backpack. It includes a built-in hydration system and multiple compartments.",
    ratings: 4.5,
    activeBids: 12,
    watchers: 90,
    totalBids: 750,
    reviews: 32,
    bidIncrementBy: 15,
    details: [
      { key: "Brand", value: "AdventureHike" },
      { key: "Model", value: "TrailBlazer 3000" },
      { key: "Color", value: "Forest Green" },
      { key: "Capacity", value: "40 liters" },
      { key: "Hydration System", value: "2L Water Bladder" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?tablets,technology",
      "https://source.unsplash.com/1920x1080/?digital,device",
      "https://source.unsplash.com/1920x1080/?screen,gadget",
    ],

    slug: "23",
    productName: "High-Performance Tablet",
    basePrice: 399.99,
    endsInHours: 48,
    description:
      "Experience high-performance computing on the go with our tablet. It's equipped with a powerful processor and a vibrant high-resolution display.",
    ratings: 4.6,
    activeBids: 16,
    watchers: 120,
    totalBids: 900,
    reviews: 42,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "TechTab" },
      { key: "Model", value: "TabX Pro" },
      { key: "Color", value: "Space Gray" },
      { key: "Processor", value: "Octa-Core CPU" },
      { key: "Display", value: "10.1 inches, 2K Resolution" },
      { key: "Storage", value: "64 GB" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?fitness-equipment,workout",
      "https://source.unsplash.com/1920x1080/?gym-machine,exercise",
      "https://source.unsplash.com/1920x1080/?training,strength",
    ],

    slug: "24",
    productName: "Multi-Function Home Gym",
    basePrice: 899.99,
    endsInHours: 72,
    description:
      "Get a complete workout with our multi-function home gym. It's perfect for strength training and comes with various exercise options.",
    ratings: 4.8,
    activeBids: 22,
    watchers: 150,
    totalBids: 1100,
    reviews: 48,
    bidIncrementBy: 40,
    details: [
      { key: "Brand", value: "FitZone" },
      {
        key: "Exercises",
        value: "Chest Press, Leg Curl, Lat Pulldown, and more",
      },
      { key: "Material", value: "Heavy-Duty Steel" },
      { key: "Weight Stack", value: "200 lbs" },
      { key: "Dimensions", value: '84" H x 48" W x 70" L' },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?television,entertainment",
      "https://source.unsplash.com/1920x1080/?smart-tv,technology",
      "https://source.unsplash.com/1920x1080/?living-room,display",
    ],

    slug: "25",
    productName: "4K Smart TV with HDR",
    basePrice: 699.99,
    endsInHours: 48,
    description:
      "Upgrade your entertainment experience with our 4K smart TV. It offers stunning picture quality and access to streaming services.",
    ratings: 4.7,
    activeBids: 18,
    watchers: 130,
    totalBids: 1000,
    reviews: 38,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "TechVision" },
      { key: "Model", value: "SmartView 4K" },
      { key: "Screen Size", value: "55 inches" },
      { key: "Resolution", value: "4K UHD with HDR" },
      { key: "Smart Features", value: "Built-in Wi-Fi, Streaming Apps" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?gaming-chair,gamer",
      "https://source.unsplash.com/1920x1080/?gaming-setup,comfort",
      "https://source.unsplash.com/1920x1080/?gaming-room,ergonomic",
    ],

    slug: "26",
    productName: "Ergonomic Gaming Chair",
    basePrice: 199.99,
    endsInHours: 36,
    description:
      "Enhance your gaming setup with our ergonomic gaming chair. It offers comfort, support, and adjustable features for long gaming sessions.",
    ratings: 4.6,
    activeBids: 14,
    watchers: 110,
    totalBids: 800,
    reviews: 32,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "GamerComfort" },
      { key: "Model", value: "ErgoGamer X1" },
      { key: "Color", value: "Red and Black" },
      { key: "Material", value: "PU Leather" },
      { key: "Features", value: "Reclining, Lumbar Support" },
      { key: "Weight Capacity", value: "250 lbs" },
    ],
  },
  {
    images: [
      "https://source.unsplash.com/1920x1080/?coffee-machine,espresso",
      "https://source.unsplash.com/1920x1080/?barista,caffeine",
      "https://source.unsplash.com/1920x1080/?coffee-shop,latte",
    ],

    slug: "27",
    productName: "Espresso Coffee Machine",
    basePrice: 299.99,
    endsInHours: 24,
    description:
      "Indulge in barista-quality coffee at home with our espresso coffee machine. It's designed for easy use and delivers rich, aromatic espresso.",
    ratings: 4.5,
    activeBids: 12,
    watchers: 90,
    totalBids: 700,
    reviews: 28,
    bidIncrementBy: 20,
    details: [
      { key: "Brand", value: "CafeMaster" },
      { key: "Model", value: "EspressoPro 200" },
      { key: "Color", value: "Stainless Steel" },
      { key: "Pressure", value: "15 Bars" },
      { key: "Milk Frother", value: "Yes" },
    ],
  },
];
