version: 3
tasks:
  default:
    cmds:
      - task -a
      
  install:
    desc: Install Dependencies
    cmds:
      - pnpm install

  start:
    desc: Start the server
    cmds:
      - pnpm dev

  build:
    desc: Build the project
    cmds:
      - pnpm build
